name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies (full)
        run: yarn

      - name: Coverage
        run: yarn coverage

      - name: Coverage Upload
        continue-on-error: true
        uses: codecov/codecov-action@v1
