name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }} # ignore commits with `[skip ci]`

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Bootstrap
        run: lerna bootstrap

      - name: Lerna Test
        run: lerna run test -- --reporters=../../jest-github-reporter.js

      - name: Coverage Upload
        continue-on-error: true
        uses: codecov/codecov-action@v1
